tasks:
  - init: |
      cat << EOF > $PWD/.env
      HOST=$(gp url 9000)
      JWT_SECRET=$(openssl rand -hex 32)
      GIMLETD_URL=
      GIMLETD_TOKEN=

      GITHUB_APP_ID=$GITHUB_APP_ID
      GITHUB_INSTALLATION_ID=$GITHUB_INSTALLATION_ID
      GITHUB_PRIVATE_KEY=$(echo $GITHUB_PRIVATE_KEY | base64 -d)
      GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      GITHUB_DEBUG=true
      GITHUB_ORG=$GITHUB_ORG

      EOF

      # Replace proxy url
      sed -i -e "s|<<REPLACE ME>>|$(gp url 9000)|" web/package.json

      # Known hosts for SSH
      sudo cp docker/known_hosts /etc/ssh/ssh_known_hosts

      # Installing Gimlet CLI
      curl -L https://github.com/gimlet-io/gimlet-cli/releases/download/v0.9.7/gimlet-$(uname)-$(uname -m) -o gimlet
      chmod +x gimlet
      sudo mv ./gimlet /usr/local/bin/gimlet
      gimlet --version

      make build-frontend build-backend
  - name: vscode settings
    init: |
      mkdir -p "$PWD/.vscode";
      cat << 'EOF' > "$PWD/.vscode/settings.json"
        {
          "terminal.integrated.fontFamily": "Monospace",
          "terminal.integrated.fontSize": 14,
        }
      EOF
      exit

ports:
  - port: 9000
    onOpen: ignore
    visibility: public
  - port: 9001
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - golang.go

gitConfig:
  alias.st: status
  alias.l: log --graph --pretty=default
  alias.lola: log --graph --oneline --all
  alias.fp: fetch --prune
