apiVersion: v1
kind: ServiceAccount
metadata:
  name: gimlet-dashboard-agent
  namespace: gimlet
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gimlet-dashboard-agent
subjects:
  - kind: ServiceAccount
    name: gimlet-dashboard-agent
    namespace: gimlet
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gimlet-agent
  namespace: gimlet
spec:
  interval: 60m
  releaseName: gimlet-agent
  chart:
    spec:
      chart: onechart
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: onechart
      interval: 10m
  values:
    serviceAccount: gimlet-dashboard-agent
    image:
      repository: ghcr.io/gimlet-io/gimlet-dashboard
      tag: agent-latest
      pullPolicy: Always
    vars:
      HOST: << url where the dash is hosted >>
      AGENT_KEY: << url where the dash is hosted >>
      ENV: << plain string of the name of the env | a key-value pair with the name of the env and the namespace to watch eg staging=gimlet-demo-staging >>
    debugSidecarEnabled: true
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "100Mi"
