---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gimlet-agent
  namespace: gimlet
spec:
  interval: 60m
  releaseName: gimlet-agent
  chart:
    spec:
      chart: onechart
      version: 0.22.0
      sourceRef:
        kind: HelmRepository
        name: onechart
      interval: 10m
  values:
    image:
      repository: ghcr.io/gimlet-io/gimlet-dashboard
      tag: agent-latest
      pullPolicy: Always
    vars:
      HOST: << url where the dash is hosted >>
      AGENT_KEY: << url where the dash is hosted >>
    debugSidecarEnabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
