name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 5

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test
